[package]
name = "randpart"
version = "0.1.0"
edition = "2021"
authors = ["welingtonpdias@proton.me"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
